set_property IOSTANDARD LVCMOS33 [get_ports {choose[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {choose[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {choose[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {choose[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {choose[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {choose[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {choose[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {choose[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]





set_property PACKAGE_PIN E3 [get_ports CLK]
set_property PACKAGE_PIN U13 [get_ports {choose[7]}]
set_property PACKAGE_PIN K2 [get_ports {choose[6]}]
set_property PACKAGE_PIN T14 [get_ports {choose[5]}]
set_property PACKAGE_PIN P14 [get_ports {choose[4]}]
set_property PACKAGE_PIN J14 [get_ports {choose[3]}]
set_property PACKAGE_PIN T9 [get_ports {choose[2]}]
set_property PACKAGE_PIN J18 [get_ports {choose[1]}]
set_property PACKAGE_PIN J17 [get_ports {choose[0]}]
set_property PACKAGE_PIN T10 [get_ports {data[7]}]
set_property PACKAGE_PIN R10 [get_ports {data[6]}]
set_property PACKAGE_PIN K16 [get_ports {data[5]}]
set_property PACKAGE_PIN K13 [get_ports {data[4]}]
set_property PACKAGE_PIN P15 [get_ports {data[3]}]
set_property PACKAGE_PIN T11 [get_ports {data[2]}]
set_property PACKAGE_PIN L18 [get_ports {data[1]}]
set_property PACKAGE_PIN H15 [get_ports {data[0]}]
